import "./globals.css";
import style from "./layout.module.css";
import { Inter } from "next/font/google";
import { Footer, Header, Sidebar } from "@/components/common";
import { MenuContextProvider } from "@/context/menu/menuContext";
import { getMenu } from "@/api/getMenu";
import { TopLevelCategory } from "@/models/IPage/IPage";
import { UpButton } from "@/components";

export const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MyTop - The best courses",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: {
  children: React.ReactNode
}) => {
  const menu = await getMenu(TopLevelCategory.Courses);

  return (
    <html lang="en">
    <body className={inter.className}>
    <MenuContextProvider menu={menu} firstCategory={TopLevelCategory.Courses}>
      <div className={style.contentWrapper}>
        <header>
          <Header className={style.header}/>
        </header>
        <aside>
          <Sidebar className={style.sidebar}/>
        </aside>
        <main>
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
        <UpButton />
      </div>
    </MenuContextProvider>
    </body>
    </html>
  );
};


export default RootLayout;
