import "./globals.css";
import style from "./layout.module.css";
import { Inter } from "next/font/google";
import { Footer, Header, Sidebar } from "@/components/common";
import { MenuContextProvider } from "@/context/menu/menuContext";
import { getMenu } from "@/api/getMenu";
import { TopLevelCategory } from "@/models/IPage/IPage";

export const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: {
  children: React.ReactNode
}) => {
  const menu = await getMenu(TopLevelCategory.Courses);

  return (
    <html lang="en">
    <body className={inter.className}>
    <MenuContextProvider menu={menu} firstCategory={TopLevelCategory.Courses}>
      <div className={style.contentWrapper}>
        <Header />
        <Sidebar />
        <main>
          {children}
        </main>
        <Footer />
      </div>
    </MenuContextProvider>
    </body>
    </html>
  );
};


export default RootLayout;
