import "./globals.css";
import { Inter } from "next/font/google";
import { Footer, Header, Sidebar } from "@/components/common";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <html lang="en">
    <body className={inter.className}>
    <div className="contentWrapper">
      <Header />
      <Sidebar />
      {children}
      <Footer />
    </div>

    </body>
    </html>
  );
};


export default RootLayout;
